### ISSUE TITLE
Safari extension is currently broken on my setup

### ISSUE THREAD

**Issue by gingerbeardman** [hawk-lord/direct-currency-converter-2#24]
It installs OK.

Safari 11.0.3 (13604.5.6)
- Setup seems OK
- extension test page shows "Unknown £"

Safari Technology Preview Release 48 (Safari 11.2, WebKit 13606.1.2.2)
- Setup seems OK
- extension test page shows "Unknown £"
- There are two sets of currency labels?

Mac OS X 10.13.3 (17D47)

**Comment by gingerbeardman** [comment]
Ah, I see you have stopped development due to your developer program membership expiring.

**Comment by hawk-lord** [comment]
Yes, I have to pay Apple 99 euros per year to release new versions of my extensions, and currently I have no incomes from the programs to pay for that.
It does not work because the data source was closed. It's fixed on Chrome, Firefox and Edge.

**Comment by gingerbeardman** [comment]
OK thanks. I'll use on Chrome when I need it.
